require 'rake/testtask'

task :default => [:unit]

desc 'run unit tests (default)'
Rake::TestTask.new(:unit) do |t|
  t.libs << "test"
  t.libs << "."
  t.test_files = FileList['test/*.rb']
  t.verbose = true
end

